Models/persona.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POOI_ProyectoVentas_AltamiranoBryan.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public persona()
        {
            this.ingreso = new HashSet<ingreso>();
        }

        public int idpersona { get; set; }

    
        public string tipo_persona { get; set; }

        
        public string nombrePersona { get; set; }

        
        public string tipo_documento { get; set; }

    
        public string num_documento { get; set; }

        
        public string direccion { get; set; }

       
        public string telefono { get; set; }

        
        public string email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ingreso> ingreso { get; set; }
    }
}

Controllers/ArticuloController.cs
using POOI_ProyectoVentas_AltamiranoBryan.Models;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;



namespace POOI_ProyectoVentas_AltamiranoBryan.Controllers
{
    public class ArticuloController : Controller
    {
        // GET: Articulo
        public ActionResult Index()
        {
            using (DbModels context = new DbModels())
            {
                return View(context.articulo.ToList());
            }
        }

        // GET: Articulo/Details/5
        public ActionResult Details(int id)
        {
            using (DbModels context = new DbModels())
            {
                var art = context.articulo.Where(x => x.idarticulo == id).FirstOrDefault();
                if (art == null)
                {
                    return HttpNotFound();
                }
                return View(art);
            }
        }

        // GET: Articulo/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Articulo/Create
        [HttpPost]
        public ActionResult Create(articulo art)
        {
            try
            {
                using (DbModels context = new DbModels())
                {
                    context.articulo.Add(art);
                    context.SaveChanges();
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Articulo/Edit/5
        public ActionResult Edit(int id)
        {
            using (DbModels context = new DbModels())
            {
                var art = context.articulo.Where(x => x.idarticulo == id).FirstOrDefault();
                if (art == null)
                {
                    return HttpNotFound();
                }
                return View(art);
            }
        }

        // POST: Articulo/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, articulo art)
        {
            try
            {
                using (DbModels context = new DbModels())
                {
                    context.Entry(art).State = EntityState.Modified;
                    context.SaveChanges();
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Articulo/Delete/5
        public ActionResult Delete(int id)
        {
            using (DbModels context = new DbModels())
            {
                var art = context.articulo.Where(x => x.idarticulo == id).FirstOrDefault();
                if (art == null)
                {
                    return HttpNotFound();
                }
                return View(art);
            }
        }

        // POST: Articulo/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                using (DbModels context = new DbModels())
                {
                    articulo art = context.articulo.Where(x => x.idarticulo == id).FirstOrDefault();
                    context.articulo.Remove(art);
                    context.SaveChanges();
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/DetalleVentaController.cs
using POOI_ProyectoVentas_AltamiranoBryan.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace POOI_ProyectoVentas_AltamiranoBryan.Controllers
{
    public class DetalleVentaController : Controller
    {
        // GET: DetalleVenta
        public ActionResult Index()
        {
            using (DbModels context = new DbModels())
            {
                var detalles = context.detalle_venta.Include(d => d.articulo).ToList();
                return View(detalles);
            }
        }

        // GET: DetalleVenta/Details/5
        public ActionResult Details(int id)
        {
            using (DbModels context = new DbModels())
            {
                var detalle = context.detalle_venta.Include(d => d.articulo).FirstOrDefault(d => d.iddetalle_venta == id);
                if (detalle == null)
                {
                    return HttpNotFound();
                }
                return View(detalle);
            }
        }

        // GET: DetalleVenta/Create
        public ActionResult Create()
        {
            using (DbModels context = new DbModels())
            {
                ViewBag.Articulos = new SelectList(context.articulo.ToList(), "idarticulo", "nombre"); // Cambia "nombre" por la propiedad correspondiente
                return View();
            }
        }

        // POST: DetalleVenta/Create
        [HttpPost]
        public ActionResult Create(detalle_venta detalle)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (DbModels context = new DbModels())
                    {
                        context.detalle_venta.Add(detalle);
                        context.SaveChanges();
                    }
                    return RedirectToAction("Index");
                }
                return View(detalle);
            }
            catch
            {
                return View();
            }
        }

        // GET: DetalleVenta/Edit/5
        public ActionResult Edit(int id)
        {
            using (DbModels context = new DbModels())
            {
                var detalle = context.detalle_venta.Include(d => d.articulo).FirstOrDefault(d => d.iddetalle_venta == id);
                if (detalle == null)
                {
                    return HttpNotFound();
                }
                ViewBag.Articulos = new SelectList(context.articulo.ToList(), "idarticulo", "nombre", detalle.idarticulo); // Cambia "nombre" por la propiedad correspondiente
                return View(detalle);
            }
        }

        // POST: DetalleVenta/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, detalle_venta detalle)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (DbModels context = new DbModels())
                    {
                        context.Entry(detalle).State = EntityState.Modified;
                        context.SaveChanges();
                    }
                    return RedirectToAction("Index");
                }
                return View(detalle);
            }
            catch
            {
                return View();
            }
        }

        // GET: DetalleVenta/Delete/5
        public ActionResult Delete(int id)
        {
            using (DbModels context = new DbModels())
            {
                var detalle = context.detalle_venta.Include(d => d.articulo).FirstOrDefault(d => d.iddetalle_venta == id);
                if (detalle == null)
                {
                    return HttpNotFound();
                }
                return View(detalle);
            }
        }

        // POST: DetalleVenta/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                using (DbModels context = new DbModels())
                {
                    var detalle = context.detalle_venta.Find(id);
                    if (detalle != null)
                    {
                        context.detalle_venta.Remove(detalle);
                        context.SaveChanges();
                    }
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/PersonaController.cs
using POOI_ProyectoVentas_AltamiranoBryan.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data.Entity;
using System.Web;
using System.Web.Mvc;

namespace POOI_ProyectoVentas_AltamiranoBryan.Controllers
{
    public class PersonaController : Controller
    {
        // GET: Persona
        public ActionResult Index()
        {
            using (DbModels context = new DbModels())
            {
                return View(context.persona.ToList());
            }
               
        }

        // GET: Persona/Details/5
        public ActionResult Details(int id)
        {
            using (DbModels context = new DbModels())
            {
                var person = context.persona.Where(x => x.idpersona == id).FirstOrDefault();
                if (person == null)
                {
                    return HttpNotFound();
                }
                return View(person);
            }

        }

        // GET: Persona/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Persona/Create
        [HttpPost]
        public ActionResult Create(persona person)
        {
            try
            {
                using (DbModels context = new DbModels())
                {
                    context.persona.Add(person);
                    context.SaveChanges();
                }

                    return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Persona/Edit/5
        public ActionResult Edit(int id)
        {
            using (DbModels context = new DbModels())
            {
                var person = context.persona.Where(x => x.idpersona == id).FirstOrDefault();
                if (person == null)
                {
                    return HttpNotFound();
                }
                return View(person);
            }
        }

        // POST: Persona/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, persona person)
        {
            try
            {
                using (DbModels context = new DbModels())
                {
                    context.Entry(person).State = EntityState.Modified;
                    context.SaveChanges();
                }

                    return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Persona/Delete/5
        public ActionResult Delete(int id)
        {
            using (DbModels context = new DbModels())
            {
                var person = context.persona.Where(x => x.idpersona == id).FirstOrDefault();
                if (person == null)
                {
                    return HttpNotFound();
                }
                return View(person);
            }
        }

        // POST: Persona/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                using (DbModels context = new DbModels())
                {
                    persona person = context.persona.Where(x => x.idpersona == id).FirstOrDefault();
                    context.persona.Remove(person);
                    context.SaveChanges();
                }
                    return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Persona/Create.cshtml
@model POOI_ProyectoVentas_AltamiranoBryan.Models.persona

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>persona</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.idpersona, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.idpersona, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.idpersona, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tipo_persona, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tipo_persona, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tipo_persona, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nombrePersona, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombrePersona, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombrePersona, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tipo_documento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tipo_documento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tipo_documento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.num_documento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.num_documento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.num_documento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.direccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.direccion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.telefono, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.telefono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Persona/Delete.cshtml
@model POOI_ProyectoVentas_AltamiranoBryan.Models.persona

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>persona</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.idpersona)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.idpersona)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tipo_persona)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tipo_persona)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nombrePersona)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombrePersona)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tipo_documento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tipo_documento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.num_documento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.num_documento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.direccion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Persona/Details.cshtml
@model POOI_ProyectoVentas_AltamiranoBryan.Models.persona

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>persona</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.idpersona)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.idpersona)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tipo_persona)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tipo_persona)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nombrePersona)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombrePersona)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tipo_documento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tipo_documento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.num_documento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.num_documento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.direccion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Persona/Edit.cshtml
@model POOI_ProyectoVentas_AltamiranoBryan.Models.persona

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>persona</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.idpersona, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.idpersona, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.idpersona, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tipo_persona, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tipo_persona, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tipo_persona, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nombrePersona, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombrePersona, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombrePersona, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tipo_documento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tipo_documento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tipo_documento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.num_documento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.num_documento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.num_documento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.direccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.direccion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.telefono, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.telefono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Persona/Index.cshtml
@model IEnumerable<POOI_ProyectoVentas_AltamiranoBryan.Models.persona>

@{
    ViewBag.Title = "Index";
}

<h2>Reporte de personas</h2>

<p>
    @Html.ActionLink("Crear nuevo objeto persona", "Create")
    <br />
    @Html.ActionLink("Ir al listado de Articulos", "Index", "Articulo")
    <br />
    @Html.ActionLink("Ir al Detalle de Venta", "Index", "DetalleVenta")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.idpersona)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tipo_persona)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nombrePersona)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tipo_documento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.num_documento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.direccion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.telefono)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.email)
        </th>
        <th>Acciones</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.idpersona)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tipo_persona)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.nombrePersona)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tipo_documento)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.num_documento)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.direccion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.telefono)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.email)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.idpersona}) |
            @Html.ActionLink("Details", "Details", new { id = item.idpersona }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.idpersona })
        </td>
    </tr>
}

</table>